#!/bin/bash

set -Ceu

image_name=bata

dir=$(cd $(dirname $(realpath $0)); pwd)

if [ $(docker images -q $image_name | wc -l) = 0 ]; then
    (
        cd $dir
        docker build -t $image_name .
    )
fi

if [ -t 1 ]; then
    docker run -it --rm -v $dir:/usr/source -v $HOME/.aws:/root/.aws $image_name python3 /usr/source/src/main.py "$@"
else
    docker run --rm -v $dir:/usr/source -v $HOME/.aws:/root/.aws $image_name python3 /usr/source/src/main.py "$@"
fi

